######################################################################
# Automatically generated by qmake (2.01a) Sat Mar 12 08:23:41 2016
######################################################################

TEMPLATE = app
TARGET = ui
DEPENDPATH += . src
INCLUDEPATH += . src

# Input
HEADERS += src/qt.h
SOURCES += src/qt.cpp \
           src/qtcell.cpp \
           src/qthtm.cpp \
           src/qtsensoryregion.cpp \
           src/qtunit.cpp
